import React from 'react';
import { Inter } from 'next/font/google';
import localFont from "next/font/local";
import { ThemeProvider } from '@/contexts/ThemeContext';
import { Header } from '@/components/Header';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayoutContent({ children }: { children: React.ReactNode }) {
  return (
    <body className={`${inter.className} ${geistSans.variable} ${geistMono.variable} bg-white dark:bg-gray-900 text-black dark:text-white`}>
      <Header />
      {children}
    </body>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <RootLayoutContent>{children}</RootLayoutContent>
      </ThemeProvider>
    </html>
  );
}
