import { 
  Diamond, 
  Bot,
  Target, 
  Globe2,
  Cpu,
  Workflow,
  Code2,
  Network,
  Shield,
  Wallet,
  Database,
  Users,
  Brain,
  Blocks,
  Network as NetworkIcon,
  Fingerprint,
  GitGraph,
  Sparkles,
  Check,
  Coins,
  Waves,
  Waves as WavesIcon,
  type LucideIcon 
} from "lucide-react"

export const Icons = {
  diamond: Diamond,
  bot: Bot,  
  target: Target,
  globe: Globe2,
  cpu: Cpu,
  workflow: Workflow,
  code: Code2,
  network: NetworkIcon,
  shield: Shield,
  wallet: Wallet,
  database: Database,
  users: Users,
  brain: Brain,  
  blocks: Blocks,  
  fingerprint: Fingerprint,  
  graph: GitGraph,  
  sparkles: Sparkles,
  check: Check,
  token: Coins,
  waves: Waves,
  wavesOff: WavesIcon,
} as const

export type IconKey = keyof typeof Icons
